# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6761082b3d5ea6fd2229b20d88eefb4eda69d171bbc047bb5ceb10c97932c39dd1077d57a30a9f32d496031032f98a1ba4177afd29c6a56048d8eca0ee2e7f23

test:
  secret_key_base: f92afb1d7a2557fba9fba791961da8b2119f9d4b13d87b00eba4fcb7121d4debd14c930758e8e87d96664a21d2973d3394cb6ee015c8e541997d86023e3c109b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
